### ISSUE TITLE
Support for real-time streaming via the SDK

### ISSUE THREAD

**Issue by pietrop** [AssemblyAI/assemblyai-node-sdk#1]
👋 Thanks for the awesome SDK!

Was wondering if you have plans for adding [support for real-time streaming](https://docs.assemblyai.com/all-guides/real-time-transcription-with-the-websocket-api) via the node the SDK?

**Comment by Swimburger** [comment]
The 2.0 release of the SDK includes a real-time transcriber. Here's a [guide on how to use it with a microphone](https://www.assemblyai.com/docs/getting-started/transcribe-streaming-audio-from-a-microphone-in-typescript), and you can also find details in the [README](https://github.com/AssemblyAI/assemblyai-node-sdk#readme).
