### ISSUE TITLE
`dist/**/*.d.ts` files appear to be incorrect

### ISSUE THREAD

**Issue by mflorence99** [AssemblyAI/assemblyai-node-sdk#14]
Version: 3.0.0

Consider line #1 in `dist/services/files/index.d.ts`: 

```typescript
import { BaseService } from "@/services/base";
```

Within the `assemblyai` project itself, paths beginning with `@/...` are resolved via its `tsconfig.json` settings. However, when user code imports the library, the following error (and many similar) is generated:

```
Cannot find module '@/services/base' or its corresponding type declarations.
```

Usage instructions in the README do not explain how to overcome these errors. What code or config changes are necessary?

**Comment by Swimburger** [comment]
Can you show me how you're using the module? I'll try to reproduce the issue.

**Comment by mflorence99** [comment]
Many thanks. Here's some minimal repro code. You can run it as follows:

```sh
npm i
npm run build
```

You should see a large number of errors like this:

```
node_modules/assemblyai/dist/services/files/index.d.ts:1:29 - 
  error TS2307: Cannot find module '@/services/base' or its corresponding type declarations.
```

**package.json**
```json
{
  "scripts": {
    "build": "tsc -p tsconfig.json"
  },
  "dependencies": {
    "@types/node": "^20.8.8",
    "assemblyai": "^3.0.0",
    "typescript": "^5.2.2"
  }
}
```

**tsconfig.json**
```json
{
  "compilerOptions": {
    "lib": ["es2022", "dom"],
    "module": "commonjs",
    "moduleResolution": "node",
    "outDir": "./build",
    "target": "es2022"
  },
  "include": ["./**/*.ts"]
}
```

**test.ts**
```typescript
import { AssemblyAI } from "assemblyai";

const client = new AssemblyAI({ apiKey: "xxx" });
```

**Comment by Swimburger** [comment]
Thanks, I can reproduce the issue. We've been using the module with other build tools, tsx, etc. which didn't reported issues like this.
There are some modules that can help you fix this, and some modules that we could add to our build system that could fix this.
However, it's easy enough for use to remove all the `@/` references and replace them with relative references, so I'll stick to the simplest solution here.

**Comment by mflorence99** [comment]
Great news, many thanks!

**Comment by mflorence99** [comment]
I can confirm that the fix works. Many thanks!
