### ISSUE TITLE
Module not found: Default condition should be last one

### ISSUE THREAD

**Issue by rekdt** [AssemblyAI/assemblyai-node-sdk#21]
The latest version 3.1.1 is throwing the below error. No issues with 3.1.0 in NextJS 13.5. 

Module not found: Default condition should be last one
> 2 | import { AssemblyAI } from 'assemblyai';
  3 | import { NextRequest, NextResponse } from "next/server";

**Comment by Swimburger** [comment]
It's odd that Next.js expects the default to be last, but it's easy enough to fix.
Thank you for reporting. I have fixed this issue and published version 3.1.2.
