### ISSUE TITLE
Cann't use the package due to internal imports

### ISSUE THREAD

**Issue by outOFFspace** [AssemblyAI/assemblyai-node-sdk#52]
I'm getting these errors while trying to use AssemblyAI.
Nest.js framework.
Node: 21.7.3.
<img width="1494" alt="Screenshot 2024-05-20 at 20 17 44" src="https://github.com/AssemblyAI/assemblyai-node-sdk/assets/3662421/25f73f91-b17d-4903-b3ca-1f2607a9077e">

**Comment by Swimburger** [comment]
How are you importing this package?
It's odd that the `src` is used when only the `dist` folder is used for exports.

**Comment by outOFFspace** [comment]
`import { AssemblyAI } from 'assemblyai';
import { EnhanceFile } from '../../files/entities/file.entity';
import { Transcript } from 'assemblyai/src';
import { TranscriptWord } from 'assemblyai/src/types/openapi.generated';
`
It seems, it only breaks, when I use Transcript type:
`import { Transcript } from 'assemblyai/src';`

**Comment by outOFFspace** [comment]
All good, IDE suggested me the wrong Transcript path:

This import works:
`import { AssemblyAI, Transcript } from 'assemblyai';`

**Comment by Swimburger** [comment]
Yeah, the types are exported at the root of the `assemblyai` module.
The module does come with the source code which is why the IDE found them and suggested them, but then the private imports from the package.json aren't considered.

let us know if you have any other questions!
