### ISSUE TITLE
Received invalid request

### ISSUE THREAD

**Issue by josiahbryan** [AssemblyAI/assemblyai-node-sdk#55]
SessionID: `d4d28b8f-1d1a-4dd4-9e1f-4444939bd59c`

Tried using both `AudioContext` / `AudioWorkletNode` to record audio (as shown in commit # `68ecdcf1643402b7baef6b70eec54a0bce62b4fb ` from `realtime-transcription-browser-js-example`, as well as using `recordrtc` as shown in `realtime-react-example` commit # `cd3aa1aad5c24e07e2c1624f5ed328c716b8c154`

No matter what I do, I get:
```log
Error: Received invalid request. Please check the documentation for the correct request schemas.
    at socket.onmessage (browser.mjs:275:1)
```

Yes, I do get a token from my backend - on the backend I get get a token for the client from `https://api.assemblyai.com/v2/realtime/token` and can confirm the token is logged and sent via the Socket, and I do get the `SessionBegins` message (hence the `SessionID` above)

Example of the core recording/transmit loop (copied from `realtime-react-example`, modified to use `RealtimeTranscriber` instead of sending a socket message itself:

```javascript

	navigator.mediaDevices
		.getUserMedia({ audio: true })
		.then((stream) => {
			microphone = new RecordRTC(stream, {
				type: 'audio',
				mimeType: 'audio/webm;codecs=pcm',
				recorderType: RecordRTC.StereoAudioRecorder,
				timeSlice: 250,
				desiredSampRate: 16000,
				numberOfAudioChannels: 1,
				bufferSize: 4096,
				audioBitsPerSecond: 128000,
				ondataavailable: (blob) => {
					const reader = new FileReader();
					reader.onload = () => {
						const base64data = reader.result;
						// console.log(`audio data:`, base64data);
						const rawBase64 = base64data
							.split('base64,')
							?.pop();
						rt.sendAudio(rawBase64);
					};
					reader.readAsDataURL(blob);
				},
			});
			microphone.startRecording();
		})
		// eslint-disable-next-line no-console
		.catch((err) => console.error(`Error from RecordRTC:`, err));
```

Thoughts? I've tried sending both the data from `reader.result` directly, as well as the processed `rawBase64` variable you see above - both get the same error. (`invalid request`). Even using the `AudioWorkletNode` gives the same error (`invalid request`) - thoughts / suggestions?

**Comment by Swimburger** [comment]
`rt.sendAudio` accepts the audio data as an array buffer, not base64-encoded string.
You could take the array buffer from the blob, and send that to `sendAudio`.

I made a PR to the sample to use the SDK. Feel free to borrow any refactoring from there for your own code.
https://github.com/AssemblyAI-Examples/realtime-react-example/pull/1

**Comment by Swimburger** [comment]
Based on our conversation in Discord, I conclude this issue has been resolved. Let us know if you have any other questions.
